[package]
name = "absentee-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
base64 = "0.22.1"
clap = { version = "4.5.32", features = ["derive"] }
config = "0.15.8"
dotenv = "0.15.0"
native-tls = "0.2.14"
serde = "1.0.218"
serde_json = "1.0.139"
